# Generated by Django 5.2.4 on 2025-08-24 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='librarian',
            options={'verbose_name': 'Librarian', 'verbose_name_plural': 'Librarians'},
        ),
        migrations.AlterModelOptions(
            name='library',
            options={'verbose_name': 'Library', 'verbose_name_plural': 'Libraries'},
        ),
    ]
